server:
  #设置端口号
  port: 8080
  session-timeout: 1800


#定义上传文件的路径
web:
  upload-path: D:/workspace/model/target/upload/

spring:
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  #设置运行环境
  profiles:
    active: dev
  #上传文件大小限制
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
  freemarker:
      template-loader-path: classpath:/template/
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html; charset=utf-8
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
  #指定上传图片静态文件的位置，用于通过url精心访问
  mvc:
    static-path-pattern: /**
  resources:
#      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
      static-locations: file:${web.upload-path}

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.yiyang.entity
  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

